name: merge

on:
  pull_request_target:
    branches:
      - master
    types:
      - opened
  issue_comment:
    branches:
      - master
    types:
      - created
  pull_request_review:
    branches:
      - master
    types:
      - submitted

jobs:
  requested:
    name: as requested code owner
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2.3.4
      - name: self merge
        uses: orta/code-owner-self-merge@1.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
