name: rebase

on:
  issue_comment:
    types:
      - created

jobs:
  pr:
    name: pull request
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: automatically rebase pull request as requested
        uses: cirrus-actions/rebase@1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
